// js/data.js

/**
 * Initial set of high-end gaming products.
 * The imageUrl paths have been updated to reference local files 
 * within the 'images/' folder of the project structure.
 */
const initialProducts = [
    // --- HIGH-END COMPONENTS ---
    {
        id: 1,
        name: "NVIDIA GeForce RTX 4090 Founders Edition",
        price: 550000, 
        category: "Graphics Cards",
        type: "GPU",
        brand: "NVIDIA",
        rating: 5,
        stock: 15,
        description: "The ultimate GeForce GPU. A quantum leap in performance, efficiency, and AI-powered graphics. Experience ultra-high performance gaming, incredibly detailed virtual worlds, and unprecedented productivity.",
        imageUrl: "images/rtx-4090.jpg", 
        features: ["24GB GDDR6X", "DLSS 3", "Ray Tracing Cores"],
        isFeatured: true,
        isTrending: true,
    },
    {
        id: 2,
        name: "AMD Radeon RX 7900 XTX Reference Card",
        price: 320000,
        category: "Graphics Cards",
        type: "GPU",
        brand: "AMD",
        rating: 4,
        stock: 22,
        description: "Experience incredible performance, visuals, and power efficiency for gaming and streaming in 4K and beyond.",
        imageUrl: "images/rx-7900-xtx.jpg",
        features: ["24GB GDDR6", "AMD FSR 3", "RDNA 3 Architecture"],
        isFeatured: false,
        isTrending: true,
    },
    
    // --- GAMING SYSTEMS ---
    {
        id: 3,
        name: "Intel Core i9-14900K Gaming PC (Custom Build)",
        price: 680000,
        category: "Gaming PCs",
        type: "PC",
        brand: "CustomBuild",
        rating: 5,
        stock: 8,
        description: "A pre-built monster PC designed for competitive 4K gaming and heavy streaming. Features liquid cooling and customizable RGB lighting.",
        imageUrl: "images/i9-gaming-pc.jpg",
        features: ["Core i9-14900K", "32GB DDR5 RAM", "2TB NVMe SSD"],
        isFeatured: true,
        isTrending: true,
    },
    {
        id: 4,
        name: "ASUS TUF Gaming A15 Laptop (RTX 4070)",
        price: 420000,
        category: "Gaming PCs",
        type: "PC",
        brand: "ASUS",
        rating: 4,
        stock: 10,
        description: "Durable and powerful gaming laptop with military-grade toughness. Excellent performance for gaming and multitasking on the go.",
        imageUrl: "images/tuf-a15-laptop.jpg",
        features: ["RTX 4070", "AMD Ryzen 9", "165Hz Display"],
        isFeatured: true,
        isTrending: false,
    },

    // --- MONITORS ---
    {
        id: 5,
        name: "ASUS ROG Swift PG27AQDM OLED Monitor",
        price: 260000,
        category: "Monitors",
        type: "Monitor",
        brand: "ASUS",
        rating: 5,
        stock: 12,
        description: "27-inch 1440p OLED gaming monitor with a stunning 240Hz refresh rate and 0.03ms response time for competitive advantage.",
        imageUrl: "images/rog-oled-monitor.jpg",
        features: ["27-inch OLED", "240Hz Refresh", "0.03ms Response"],
        isFeatured: true,
        isTrending: true,
    },
    {
        id: 6,
        name: "Samsung Odyssey G9 49-inch Ultrawide",
        price: 350000,
        category: "Monitors",
        type: "Monitor",
        brand: "Samsung",
        rating: 4,
        stock: 7,
        description: "Massive 49-inch curved ultrawide display for ultimate immersion. 240Hz refresh rate and 1ms response time.",
        imageUrl: "images/odyssey-g9.jpg",
        features: ["49-inch Curved", "240Hz", "QLED"],
        isFeatured: false,
        isTrending: false,
    },

    // --- CONSOLES ---
    {
        id: 7,
        name: "Sony PlayStation 5 (Disc Edition)",
        price: 185000,
        category: "Consoles",
        type: "Console",
        brand: "Sony",
        rating: 5,
        stock: 30,
        description: "Experience lightning-fast loading with an ultra-high speed SSD, haptic feedback, adaptive triggers and 3D Audio.",
        imageUrl: "images/ps5-console.jpg",
        features: ["Ultra-High Speed SSD", "Ray Tracing", "Tempest 3D AudioTech"],
        isFeatured: true,
        isTrending: false,
    },
    {
        id: 8,
        name: "Microsoft Xbox Series X",
        price: 175000,
        category: "Consoles",
        type: "Console",
        brand: "Microsoft",
        rating: 4,
        stock: 25,
        description: "The fastest, most powerful Xbox ever. True 4K gaming, up to 120 frames per second, and 12 teraflops of graphic processing power.",
        imageUrl: "images/xbox-series-x.jpg",
        features: ["12 TFLOPS GPU", "Velocity Architecture", "Quick Resume"],
        isFeatured: false,
        isTrending: true,
    },

    // --- ACCESSORIES ---
    {
        id: 9,
        name: "Razer BlackShark V2 Pro Wireless Headset",
        price: 45000,
        category: "Gaming Accessories",
        type: "Accessories",
        brand: "Razer",
        rating: 4,
        stock: 50,
        description: "The definitive e-sports headset. Unstoppable audio, crystal-clear mic, and all-day comfort for marathon gaming sessions.",
        imageUrl: "images/blackshark-v2-pro.jpg",
        features: ["HyperSpeed Wireless", "THX Spatial Audio", "FlowKnit Ear Cushions"],
        isFeatured: false,
        isTrending: true,
    },
    {
        id: 10,
        name: "Logitech G Pro X Superlight Mouse",
        price: 35000,
        category: "Gaming Accessories",
        type: "Accessories",
        brand: "Logitech",
        rating: 5,
        stock: 60,
        description: "Designed with pros, engineered to win. Ultra-lightweight wireless mouse under 63 grams.",
        imageUrl: "images/g-pro-x-mouse.jpg",
        features: ["<63g Weight", "LIGHTSPEED Wireless", "HERO 25K Sensor"],
        isFeatured: true,
        isTrending: false,
    },
    {
        id: 11,
        name: "SteelSeries Apex Pro Mini Wireless Keyboard",
        price: 55000,
        category: "Gaming Accessories",
        type: "Accessories",
        brand: "SteelSeries",
        rating: 4,
        stock: 40,
        description: "The fastest keyboard in the world. Adjustable mechanical switches for customized actuation.",
        imageUrl: "images/apex-pro-mini.jpg",
        features: ["OmniPoint 2.0 Switches", "60% Form Factor", "Quantum 2.0 Wireless"],
        isFeatured: false,
        isTrending: true,
    },
    {
        id: 12,
        name: "Elgato Stream Deck XL",
        price: 70000,
        category: "Gaming Accessories",
        type: "Accessories",
        brand: "Elgato",
        rating: 4,
        stock: 18,
        description: "Your fingers are flying. Live production controller with 32 customizable keys for streamers and content creators.",
        imageUrl: "images/stream-deck-xl.jpg",
        features: ["32 Customizable LCD Keys", "Direct Integration", "Instant Mute/Scenes"],
        isFeatured: false,
        isTrending: false,
    },
];